professions:
  - engineer
  - medic
  - labourer
  - pilot
  - hunter
tiers:
  0:
    name: unskilled
    maxlevel: 1
  1:
    name: novice
    maxlevel: 20
  2:
    name: adept
    maxlevel: 40
  3:
    name: expert
fatigue_time: 86400000
permission_prefix: horizonprofessions
max_exp: 100
claimable_tiers: 3
tier_cap: 6
place_cooldown: 3600000
slaying:
damageModifier:
healing:
recipes:
breakBlocks:
placeBlocks: