slaying:
  chicken:
    profession: hunter
    exp: 1
  pig:
    profession: hunter
    exp: 1
  sheep:
    profession: hunter
    exp: 1
  cow:
    profession: hunter
    exp: 1
  squid:
    profession: hunter
    exp: 1
  mushroom_cow:
    profession: hunter
    exp: 1
  spider:
    profession: hunter
    exp: 5
  creeper:
    profession: hunter
    exp: 10
  skeleton:
    profession: hunter
    exp: 10
  giant:
    profession: hunter
    exp: 50
  slime:
    profession: hunter
    exp: 5
  ghast:
    profession: hunter
    exp: 50
  pig_zombie:
    profession: hunter
    exp: 10
  enderman:
    profession: hunter
    exp: 10
  cave_spider:
    profession: hunter
    exp: 10
  silverfish:
    profession: hunter
    exp: 5
  blaze:
    profession: hunter
    exp: 10
  magma_cube:
    profession: hunter
    exp: 10
  ender_dragon:
    profession: hunter
    exp: 50
  wolf:
    profession: hunter
    exp: 10
  snowman:
    profession: hunter
    exp: 1
  villager:
    profession: hunter
    exp: 1
healing:
  paper:
    profession: medic
    exp: 5
    tier:
      novice: 2
      adept: 4
      expert: 6
recipes:
  engineer:
    diode: 5
professions:
  - engineer
  - medic
  - labourer
  - pilot
  - hunter
tiers:
  0:
    name: unskilled
    maxlevel: 1
  1:
    name: novice
    maxlevel: 20
  2:
    name: adept
    maxlevel: 40
  3:
    name: expert
fatigue_time: 86400000
max_exp: 100
claimable_tiers: 3