professions:
  - engineer
  - medic
  - labourer
  - pilot
  - hunter
tiers:
  0:
    name: unskilled
    maxLevel: 1
  1:
    name: novice
    maxLevel: 20
  2:
    name: adept
    maxLevel: 40
  3:
    name: expert
fatigue_time: 86400000
permission_prefix: horizonprofessions
enable_training: true
max_exp: 1000
claimable_tiers: 3
tier_cap: 6
place_cooldown: 3600000
slaying:
damageModifier:
healing:
recipes:
breakBlocks:
placeBlocks: