name: Horizon_Professions
main: com.gmail.Rhisereld.Horizon_Professions.Main
version: 1.0
depend: [Vault]
softdepend: [RecipeManager]
commands:
  profession:
    description: All Horizon Profession commands.
    aliases: hp
    permissions: horizon_professions.help

permissions:
  horizon_professions.*:
    description: Gives access to all Horizon Profession commands.
    children:
      horizon_professions.help: true
      horizon_professions.help.admin: true
      horizon_professions.view: true
      horizon_professions.view.admin: true
      horizon_professions.forget: true
      horizon_professions.forget.admin: true
      horizon_professions.givetier: true
      horizon_professions.claimtier: true
      horizon_professions.reset: true
      horizon_professions.reset.admin: true
      horizon_professions.train: true
      horizon_professions.train.admin: true
      
  horizon_professions.admin:
    description: Gives access to all Horizon Profession commands for admins and normal players.
    children:
      horizon_professions.help: true
      horizon_professions.help.admin: true
      horizon_professions.view: true
      horizon_professions.view.admin: true
      horizon_professions.forget: true
      horizon_professions.forget.admin: true
      horizon_professions.givetier: true
      horizon_professions.claimtier: true
      horizon_professions.reset: true
      horizon_professions.reset.admin: true
      horizon_professions.train: true
      horizon_professions.train.admin: true

  horizon_professions.common:
    description: Access to Horizon Profession for normal players.
    children:
      horizon_professions.help: true
      horizon_professions.view: true
      horizon_professions.forget: true
      horizon_professions.claimtier: true
      horizon_professions.reset: true
      horizon_professions.train: true