name: HorizonProfessions
main: io.github.LonelyNeptune.HorizonProfessions.Main
version: 1.1
depend: [Vault]
softdepend: [RecipeManager]
commands:
  profession:
    description: All Horizon Profession commands.
    aliases: prof
    permissions: horizonprofessions.help

permissions:
  horizonprofessions.*:
    description: Gives access to all Horizon Profession commands.
    children:
      horizonprofessions.help: true
      horizonprofessions.help.admin: true
      horizonprofessions.view: true
      horizonprofessions.view.admin: true
      horizonprofessions.forget: true
      horizonprofessions.forget.admin: true
      horizonprofessions.givetier: true
      horizonprofessions.claimtier: true
      horizonprofessions.reset: true
      horizonprofessions.reset.admin: true
      horizonprofessions.train: true
      horizonprofessions.train.admin: true
      horizonprofessions.reload: true
      
  horizonprofessions.admin:
    description: Gives access to all Horizon Profession commands for admins and normal players.
    children:
      horizonprofessions.help: true
      horizonprofessions.help.admin: true
      horizonprofessions.view: true
      horizonprofessions.view.admin: true
      horizonprofessions.forget: true
      horizonprofessions.forget.admin: true
      horizonprofessions.givetier: true
      horizonprofessions.claimtier: true
      horizonprofessions.reset: true
      horizonprofessions.reset.admin: true
      horizonprofessions.train: true
      horizonprofessions.train.admin: true

  horizonprofessions.common:
    description: Access to Horizon Profession for normal players.
    children:
      horizonprofessions.help: true
      horizonprofessions.view: true
      horizonprofessions.forget: true
      horizonprofessions.claimtier: true
      horizonprofessions.reset: true
      horizonprofessions.train: true